runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "1.4"

- name: MySQLdb
  version: "latest"

- name: pycrypto
  version: "2.6"

- name: ssl
  version: "2.7.11"

env_variables:
  DJANGO_SETTINGS_MODULE: "burnhamx.settings"

handlers:
- url: /static
  static_dir: static
  expiration: '0'

- url: /static/admin
  static_dir: static/admin
  expiration: '0'

- url: /favicon\.ico
  static_files: static/images/fav.ico
  upload: static/images/fav.ico
  expiration: '0'

- url: /.*
  script: main.application
  secure: always



